import type React from "react";

export const s = {
  label: {
    display: "block",
    fontSize: "11px",
    color: "#64748b",
    marginBottom: "4px",
    textTransform: "uppercase" as const,
    letterSpacing: "0.5px",
  },
  input: {
    width: "100%",
    padding: "8px 12px",
    background: "#0f172a",
    border: "1px solid #334155",
    borderRadius: "6px",
    color: "#e2e8f0",
    fontSize: "14px",
    outline: "none",
    boxSizing: "border-box" as const,
  },
  textarea: {
    width: "100%",
    padding: "10px 12px",
    background: "#0f172a",
    border: "1px solid #334155",
    borderRadius: "6px",
    color: "#e2e8f0",
    fontSize: "14px",
    outline: "none",
    resize: "vertical" as const,
    fontFamily: "inherit",
    lineHeight: "1.5",
    boxSizing: "border-box" as const,
  },
  select: {
    width: "100%",
    padding: "8px 12px",
    background: "#0f172a",
    border: "1px solid #334155",
    borderRadius: "6px",
    color: "#e2e8f0",
    fontSize: "14px",
    outline: "none",
  },
  card: {
    background: "#1e293b",
    border: "1px solid #334155",
    borderRadius: "12px",
    padding: "20px",
    marginBottom: "16px",
  } as React.CSSProperties,
  btnPrimary: {
    padding: "8px 20px",
    background: "#a78bfa",
    color: "#0f172a",
    border: "none",
    borderRadius: "6px",
    fontWeight: 600,
    fontSize: "13px",
    cursor: "pointer",
  } as React.CSSProperties,
  btnSecondary: {
    padding: "8px 16px",
    background: "transparent",
    color: "#94a3b8",
    border: "1px solid #334155",
    borderRadius: "6px",
    fontSize: "13px",
    cursor: "pointer",
  } as React.CSSProperties,
  btnDanger: {
    padding: "6px 14px",
    background: "rgba(220,38,38,0.15)",
    color: "#f87171",
    border: "1px solid rgba(220,38,38,0.3)",
    borderRadius: "6px",
    fontSize: "12px",
    cursor: "pointer",
  } as React.CSSProperties,
  sectionLabel: {
    fontSize: "11px",
    color: "#64748b",
    textTransform: "uppercase" as const,
    letterSpacing: "0.5px",
    marginBottom: "12px",
  },
};
